### PR TITLE
Improves README.

### PR DESCRIPTION
**Pull request by francocipollone**
Part of https://github.com/maliput/maliput_documentation/issues/100

### Summary
This PR improves the README file:

- Providing information about installation via binaries.
- Providing information about installation via sources.
- Linking to online documentation

### CODE REVIEW

**Review by agalbachicar — APPROVED** [review]
LGTM.

however, we should check https://build.ros2.org/job/Fpr__maliput_integration_tests__ubuntu_focal_amd64/1/testReport/junit/projectroot/test/derive_lane_s_routes_test/ which shows failing tests due to bad files.

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
CI is finally fixed, going in!

**Pull request merged**
